// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if(kIsWeb) {
      return web;
    }

    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyF0CsQuZWz9KCmXMBElYv6gcBHD01Qeg',
    appId: '1:374735603796:web:2ff55116f73ba59fc985c1',
    messagingSenderId: '374735603796',
    projectId: 'waitforme-9d678',
    authDomain: 'waitforme-9d678.firebaseapp.com',
    storageBucket: 'waitforme-9d678.appspot.com',
    measurementId: 'G-BT267J2Q63',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvjJuWHeiwRkfbmpGKTtxnphgUzxvg-XU',
    appId: '1:374735603796:android:b0cc9b0f9646f88fc985c1',
    messagingSenderId: '374735603796',
    projectId: 'waitforme-9d678',
    storageBucket: 'waitforme-9d678.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgqIA_-aAFBen1ziwIfzo-MSnUJOYnhZw',
    appId: '1:374735603796:ios:2a86ac57707ccd8fc985c1',
    messagingSenderId: '374735603796',
    projectId: 'waitforme-9d678',
    storageBucket: 'waitforme-9d678.appspot.com',
    iosBundleId: 'com.example.waitForMe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgqIA_-aAFBen1ziwIfzo-MSnUJOYnhZw',
    appId: '1:374735603796:ios:e3cf71f16a8ebbafc985c1',
    messagingSenderId: '374735603796',
    projectId: 'waitforme-9d678',
    storageBucket: 'waitforme-9d678.appspot.com',
    iosBundleId: 'com.example.waitForMe.RunnerTests',
  );

}